-- ============================================================
-- Ateeqo: Random reviews per product (10 to 20 each)
-- Har product pe ALAG review texts + reviewers (no same set)
-- Avg rating ~4 to 5
--
-- IMPORTANT: pehle purani reviews clear karta hai
-- Run on LIVE DB via phpMyAdmin / MySQL.
-- ============================================================

START TRANSACTION;

DELETE FROM product_reviews;

DROP TEMPORARY TABLE IF EXISTS tmp_reviewers;
CREATE TEMPORARY TABLE tmp_reviewers (
  rid INT NOT NULL PRIMARY KEY,
  reviewer VARCHAR(100) NOT NULL
);
INSERT INTO tmp_reviewers (rid, reviewer) VALUES
(1, 'Ayesha Khan'),
(2, 'Fatima Ali'),
(3, 'Hira Ahmed'),
(4, 'Sana Malik'),
(5, 'Zara Hussain'),
(6, 'Maryam Iqbal'),
(7, 'Nimra Sheikh'),
(8, 'Laiba Raza'),
(9, 'Mehwish Noor'),
(10, 'Anam Batool'),
(11, 'Sara Javed'),
(12, 'Iqra Siddiqui'),
(13, 'Mahnoor Asif'),
(14, 'Amna Rehman'),
(15, 'Bushra Tariq'),
(16, 'Rabia Nadeem'),
(17, 'Saima Farooq'),
(18, 'Kiran Shah'),
(19, 'Nadia Qureshi'),
(20, 'Hina Imran'),
(21, 'Aleena Butt'),
(22, 'Kinza Mir'),
(23, 'Eman Haider'),
(24, 'Momina Saad'),
(25, 'Areeba Yousaf'),
(26, 'Umaima Khalid'),
(27, 'Dua Zeeshan'),
(28, 'Hafsa Bilal'),
(29, 'Mishal Aslam'),
(30, 'Sundas Adeel'),
(31, 'Ali Raza'),
(32, 'Usman Khan'),
(33, 'Hassan Ali'),
(34, 'Bilal Ahmed'),
(35, 'Hamza Malik'),
(36, 'Ahmed Sheikh'),
(37, 'Omar Farooq'),
(38, 'Saad Iqbal'),
(39, 'Zain Abbas'),
(40, 'Fahad Hussain'),
(41, 'Taha Rehman'),
(42, 'Arsalan Shah'),
(43, 'Waleed Butt'),
(44, 'Danish Qureshi'),
(45, 'Noman Siddiqui'),
(46, 'Shahzaib Noor'),
(47, 'Haris Jamil'),
(48, 'Rizwan Asif'),
(49, 'Sameer Tariq'),
(50, 'Yasir Imran'),
(51, 'Amina Chaudhry'),
(52, 'Fariha Gul'),
(53, 'Komal Nisar'),
(54, 'Shazia Pervez'),
(55, 'Tehreem Aziz'),
(56, 'Bismah Latif'),
(57, 'Rida Kamran'),
(58, 'Maham Shakeel'),
(59, 'Noor Fatima'),
(60, 'Eshaal Virk'),
(61, 'Saba Anwar'),
(62, 'Lubna Saeed'),
(63, 'Ghazala Mir'),
(64, 'Samina Akhtar'),
(65, 'Nida Jamil'),
(66, 'Iqbal Hussain'),
(67, 'Kamran Malik'),
(68, 'Junaid Akram'),
(69, 'Asad Mehmood'),
(70, 'Imran Baig'),
(71, 'Farhan Latif'),
(72, 'Adeel Mirza'),
(73, 'Shahid Anwar'),
(74, 'Naveed Gul'),
(75, 'Kashif Rauf'),
(76, 'Mariam Gulzar'),
(77, 'Hoorain Shah'),
(78, 'Alishba Tariq'),
(79, 'Zoya Naeem'),
(80, 'Hania Rauf'),
(81, 'Esha Khan'),
(82, 'Minahil Asif'),
(83, 'Aleesha Noor'),
(84, 'Rameen Ali'),
(85, 'Sabeeka Fatima'),
(86, 'Wania Ahmed'),
(87, 'Manahil Iqbal'),
(88, 'Aroosh Khan'),
(89, 'Palwasha Shah'),
(90, 'Khadija Noor');

DROP TEMPORARY TABLE IF EXISTS tmp_review_texts;
CREATE TEMPORARY TABLE tmp_review_texts (
  tid INT NOT NULL PRIMARY KEY,
  review_text TEXT NOT NULL
);
INSERT INTO tmp_review_texts (tid, review_text) VALUES
(1, 'Bohot zabardast bag hai, quality bilkul premium lagi. Delivery bhi time pe aa gayi.'),
(2, 'Material soft aur strong hai. Roz ke use ke liye perfect hai.'),
(3, 'Color pics jaisa hi aaya. Size bhi theek hai, recommended!'),
(4, 'Pehle thora doubt tha lekin milne ke baad bohot acha laga. Worth the price.'),
(5, 'Stitching clean hai aur zip smoothly chalti hai. Happy with purchase.'),
(6, 'Gift ke liye liya tha, unko bohot pasand aaya. Packaging bhi achi thi.'),
(7, 'Daily office use me chal raha hai, spacious aur stylish dono.'),
(8, 'Kapra soft hai, look classy hai. Ateeqo se phir order karungi.'),
(9, 'Price ke hisaab se quality bohot better hai. Satisfied customer.'),
(10, 'Strap comfortable hai, lambi walk pe bhi shoulder me dard nahi hota.'),
(11, 'Design unique hai, market me common bags se alag lagta hai.'),
(12, 'Colour fade nahi hua wash ke baad. Quality solid hai.'),
(13, 'Delivery fast thi aur bag bilkul new condition me mila.'),
(14, 'Size perfect hai phone, wallet, makeup sab comfortably aa jata hai.'),
(15, 'Friend ne recommend kiya tha, ab main bhi recommend karti hun.'),
(16, 'Finishing bohot neat hai. Photos se better lag raha hai real me.'),
(17, 'Pehli baar order kiya, experience acha raha. Definitely buying again.'),
(18, 'Zip aur lining dono durable lagte hain. Value for money.'),
(19, 'Style modern hai, casual aur formal dono ke sath match ho jata hai.'),
(20, 'Customer service bhi responsive thi. Overall 10/10 experience.'),
(21, 'MashaAllah bohot pyara bag hai, compliments milte hain.'),
(22, 'Quality expectations se better hai. Will shop again soon.'),
(23, 'Inner pocket useful hai, organization easy ho gayi.'),
(24, 'Simple, elegant, aur durable — exactly what I wanted.'),
(25, 'Lahore me milne wale bags se farq clear hai. Recommended.'),
(26, 'Karachi se order kiya, packing safe thi aur bag scratch-free mila.'),
(27, 'Weight light hai, lekin look heavy-duty lagta hai. Love it.'),
(28, 'Cousins ne bhi yehi bag mangwaya after seeing mine.'),
(29, 'Handle grip soft hai, lamba use easy rehta hai.'),
(30, 'Black color me liya — har outfit ke sath chalta hai.'),
(31, 'Beige tone bohot soft aur classy nikla. Happy purchase.'),
(32, 'Office bag ke tor pe use kar rahi hun, perfect capacity.'),
(33, 'Travel pe le gayi, laptop pouch ke sath bhi fit ho gaya.'),
(34, 'Zipper quality premium hai, stuck nahi hota.'),
(35, 'Lining soft aur clean hai, andar se bhi neat finishing.'),
(36, 'Pehle cheap bag use karti thi, farq clear feel hota hai.'),
(37, 'Shaadi function me use kiya, bohot elegant lag raha tha.'),
(38, 'College ke liye liya, books aur bottle dono aa jate hain.'),
(39, 'Colour exact same tha as website photo. No disappointment.'),
(40, 'Strap adjustable hai, height apne hisaab se set kar sakti hun.'),
(41, 'Husband ne gift diya tha Ateeqo se — mujhe bohot pasand aaya.'),
(42, 'Second order hai mera, pehli wali quality same level pe hai.'),
(43, 'Smell bilkul nahi thi new bag ki, clean feel aaya.'),
(44, 'Corner stitching strong hai, tear hone ka khauf nahi.'),
(45, 'Minimal design hai lekin statement piece lagta hai.'),
(46, 'Budget friendly hone ke bawajood luxury feel deta hai.'),
(47, 'Return nahi karna para, size aur color dono perfect.'),
(48, 'WhatsApp pe confirm kiya tha, reply jaldi aaya. Good service.'),
(49, 'COD se liya tha, experience smooth raha end to end.'),
(50, 'Rainy day pe use kiya, thori moisture se damage nahi hua.'),
(51, 'Kids ke saman ke liye bhi use kar leti hun, spacious hai.'),
(52, 'Gold hardware shine karta hai, sasta nahi lagta.'),
(53, 'Monogram style bohot trendy hai is season.'),
(54, 'Tote size ideal hai shopping aur daily commute dono ke liye.'),
(55, 'Crossbody me convert kar ke use kiya, comfortable raha.'),
(56, 'Shoulder pe long wear ke baad bhi mark nahi chorta.'),
(57, 'Friends group me sab ne price poocha — worth it bola.'),
(58, 'Pehle fake brands try kiye, ab Ateeqo pe settle hun.'),
(59, 'Dust bag ke sath aaya, storage easy ho gayi.'),
(60, 'Color combination soft hai, overpowering nahi.'),
(61, 'Work meetings me le jati hun, professional look aata hai.'),
(62, 'Picnic pe bhi use hua, easy wipe clean material.'),
(63, 'Zip pockets alag hain, keys aur cards safe rehte hain.'),
(64, 'Bottom base strong hai, bag khara rehta hai table pe.'),
(65, 'Thread quality achi hai, loose ends nahi hain.'),
(66, 'Size guide follow ki, perfect fit mila. Thanks Ateeqo.'),
(67, 'Gift wrap option nahi tha lekin packaging khud presentable thi.'),
(68, 'Multan se order kiya, 3 din me mil gaya. Fast!'),
(69, 'Islamabad delivery on time thi. Product as described.'),
(70, 'Rawalpindi wale cousin ne recommend kiya tha. Spot on.'),
(71, 'Faisalabad se first online bag order — experience positive.'),
(72, 'Peshawar delivery safe thi, box me bubble wrap tha.'),
(73, 'Quetta se order kiya, thora late mila lekin quality top.'),
(74, 'Hyderabad Sindh se liya, packaging zabardast thi.'),
(75, 'Sialkot me friends ke sath compare kiya — ye best nikla.'),
(76, 'Gujranwala se reorder plan kar rahi hun dusre color ka.'),
(77, 'Bahawalpur delivery smooth rahi. Bag soft aur classy.'),
(78, 'Abbottabad trip pe le gayi, hiking ke saath bhi chal gaya.'),
(79, 'Murree cold me bhi strap soft raha, no crack.'),
(80, 'Wedding season me bohot kaam aaya, matching outfits ke sath.'),
(81, 'Eid pe gift kiya, receiver khush ho gaye.'),
(82, 'Anniversary gift banaya, wife ko style pasand aa gaya.'),
(83, 'Mother ke liye liya — unko comfort aur look dono chahiye the.'),
(84, 'Sister ne borrow kiya aur wapas nahi kar rahi, lol.'),
(85, 'Office colleagues ne poocha kahan se liya. Proud moment.'),
(86, 'Instagram pe dekha tha pehle, real me better hai.'),
(87, 'TikTok reviews dekh ke liya, genuine product mila.'),
(88, 'YouTube unboxing jaisa feel aaya open karte waqt.'),
(89, 'Price drop sale pe liya, deal of the month feel hua.'),
(90, 'Original price se discount pe mila, quality same premium.'),
(91, 'Stock me last piece tha almost, lucky timing.'),
(92, 'Waitlist pe nahi jana para, instantly available tha.'),
(93, 'Size medium perfect for petite frame. Not bulky.'),
(94, 'Tall height pe bhi proportion sahi lagta hai.'),
(95, 'Neutral color wardrobe me easily blend ho jata hai.'),
(96, 'Bold print wala version bhi try karungi next time.'),
(97, 'Leather-like feel hai without heavy maintenance.'),
(98, 'Wipe with damp cloth — clean ho jata hai easily.'),
(99, 'No weird chemical smell after unboxing. Fresh.'),
(100, 'Hardware screws tight hain, loose nahi hote.'),
(101, 'Magnet closure strong hai, accidental open nahi hota.'),
(102, 'Drawstring + zip combo practical hai daily use me.'),
(103, 'Side pockets water bottle ke liye perfect size.'),
(104, 'Main compartment deep hai, laptop 13 inch aa jata hai.'),
(105, 'Tablet aur charger dono fit ho gaye comfortably.'),
(106, 'Makeup pouch alag rakhne ki jagah mil gayi andar.'),
(107, 'Umbrella fit ho jati hai side me without bulging.'),
(108, 'Grocery light run pe bhi use kar leti hun.'),
(109, 'Bank documents ke liye formal look deta hai.'),
(110, 'Court visit pe professional aur neat lagta hai.'),
(111, 'University library days me bohot kaam aaya.'),
(112, 'Exam season me notes carry karne ke liye ideal.'),
(113, 'Internship interviews me confidence boost diya look ne.'),
(114, 'First job gift to myself — zero regrets.'),
(115, 'Promotion celebrate karne pe khud ko gift kiya.'),
(116, 'Self-care purchase feel hua, mood lift hua.'),
(117, 'Rain cover nahi chahiye tha, material water resistant.'),
(118, 'Dust resistant surface, white clothes pe mark nahi.'),
(119, 'Pet hair easily nikal jata hai brush se.'),
(120, 'Kids sticky hands se bhi wipe clean easy.'),
(121, 'Gym ke kapre + bottle comfortably aa jate hain.'),
(122, 'Yoga class pe mat strap ke sath chal gaya.'),
(123, 'Brunch dates pe cute aur practical dono.'),
(124, 'Dinner outings me clutch ki jagah ye use karti hun.'),
(125, 'Cinema night pe popcorn ke sath bhi manage ho gaya.'),
(126, 'Concert pe secure feel hua, zip locked.'),
(127, 'Airport carry-on personal item ke tor pe perfect.'),
(128, 'Flight me under seat fit ho gaya easily.'),
(129, 'Road trip pe maps aur snacks ke liye roomy.'),
(130, 'Beach day pe sand easy clean — no drama.'),
(131, 'Hill station trip pe photos me bohot acha dikha.'),
(132, 'Family picnic pe shared snacks ke liye useful.'),
(133, 'Iftar gathering me elegantly match kiya outfit.'),
(134, 'Mehndi function me color theme ke sath perfect.'),
(135, 'Baraat pe gift bag ke sath stylish lag raha tha.'),
(136, 'Walima guest look complete kar diya is bag ne.'),
(137, 'Reception pe heels ke sath balance acha tha.'),
(138, 'Nikah ceremony me soft pastel tone shine kiya.'),
(139, 'Mayun pe floral dress ke sath cute combo bana.'),
(140, 'Dholki night me friends ne borrow request ki.'),
(141, 'Beautiful bag with great craftsmanship. Feels premium in hand.'),
(142, 'Love the design and the quality of the fabric. Highly recommend.'),
(143, 'Perfect everyday tote. Spacious, stylish, and well made.'),
(144, 'Excellent purchase. The stitching is neat and the color is lovely.'),
(145, 'Arrived quickly and looks exactly like the photos. Very happy.'),
(146, 'Comfortable to carry and surprisingly roomy. Great value.'),
(147, 'The finish is clean and elegant. Will order more colors soon.'),
(148, 'Solid quality for the price. My new go-to bag for work.'),
(149, 'Looks expensive and feels durable. Impressed with Ateeqo.'),
(150, 'Soft material, strong straps, and a classy look. Five stars.'),
(151, 'Great gift option. Packaging was neat and product was perfect.'),
(152, 'Lightweight yet sturdy. Perfect for daily use around the city.'),
(153, 'The details are thoughtfully done. Feels like a premium brand.'),
(154, 'Color is rich and the size is just right. Totally satisfied.'),
(155, 'Bought it for travel and it held up really well. Recommended.'),
(156, 'The hardware feels solid and the zippers glide smoothly.'),
(157, 'I get compliments every time I carry this bag out.'),
(158, 'Neutral shade that matches almost everything in my wardrobe.'),
(159, 'Roomy enough for work essentials without looking bulky.'),
(160, 'The lining is soft and well finished inside and out.'),
(161, 'Straps sit comfortably on the shoulder for long hours.'),
(162, 'Better than several higher-priced bags I have owned.'),
(163, 'Clean silhouette with just the right amount of structure.'),
(164, 'Quick delivery and careful packing. Product arrived flawless.'),
(165, 'Exactly the everyday luxury piece I was looking for.'),
(166, 'Holds my wallet, phone, keys, and a small pouch with ease.'),
(167, 'The color depth is richer in person than online photos.'),
(168, 'Great balance of fashion and function for office days.'),
(169, 'I ordered a second one in another color after one week.'),
(170, 'Feels soft to touch but still keeps its shape nicely.'),
(171, 'No loose threads or uneven stitching anywhere. Quality work.'),
(172, 'A reliable bag for commuting, meetings, and weekends.'),
(173, 'The base is firm so it stands upright when placed down.'),
(174, 'Magnetic closure is strong enough without being hard to open.'),
(175, 'Interior pockets are placed thoughtfully for daily organization.'),
(176, 'Perfect gift for my sister — she loved the packaging too.'),
(177, 'Looks polished with both jeans and formal wear.'),
(178, 'After two months of daily use, it still looks new.'),
(179, 'The proportion is flattering and not oversized.'),
(180, 'Worth every rupee for the craftsmanship alone.'),
(181, 'Customer support answered sizing questions promptly.'),
(182, 'Soft handles that do not dig into the shoulder.'),
(183, 'A timeless design rather than a short-lived trend.'),
(184, 'Surprisingly lightweight for how spacious it feels.'),
(185, 'The monogram detail is subtle and elegant.'),
(186, 'Ideal size for travel as a personal cabin bag.'),
(187, 'Fabric feels premium and resists everyday scuffs well.'),
(188, 'I compared three brands — Ateeqo won on finish quality.'),
(189, 'Secure zippers give peace of mind in crowded places.'),
(190, 'The bag elevates even a simple outfit instantly.'),
(191, 'Excellent stitching around stress points and corners.'),
(192, 'Neutral enough for work, stylish enough for evenings.'),
(193, 'No chemical smell on arrival — fresh and clean.'),
(194, 'Capacity is honest; what you see is what you get.'),
(195, 'A thoughtful purchase that I use almost every day.'),
(196, 'The strap length works well for my height.'),
(197, 'Edges are finished cleanly with no fraying so far.'),
(198, 'Pairs beautifully with both casual and formal shoes.'),
(199, 'I appreciate the understated branding approach.'),
(200, 'Strong seams — I load it fairly heavily without worry.'),
(201, 'The shape holds up even when the bag is full.'),
(202, 'A refined look that does not scream for attention.'),
(203, 'Delivery tracking was clear and arrival was on schedule.'),
(204, 'Exactly as described — rare and refreshing online.'),
(205, 'Soft structure that still feels intentional and designed.'),
(206, 'Great everyday companion for city errands and office.'),
(207, 'The interior is dark enough to hide minor marks.'),
(208, 'Hardware tone matches the body color perfectly.'),
(209, 'I would confidently gift this to a picky friend.'),
(210, 'Comfortable cross-body conversion when I need hands free.'),
(211, 'Premium feel without the premium brand markup.'),
(212, 'The bag photographs beautifully for content days too.'),
(213, 'Durable enough for weekly travel between cities.'),
(214, 'A calm, elegant aesthetic that ages well.'),
(215, 'Fits my 13-inch laptop sleeve without stretching.'),
(216, 'The weight distribution is comfortable on long walks.'),
(217, 'Simple care — a soft wipe keeps it looking fresh.'),
(218, 'I notice the quality every time I open and close it.'),
(219, 'Balanced proportions — neither tiny nor oversized.'),
(220, 'Became my default bag within the first week.'),
(221, 'Quality bohot solid hai, roz use ke baad bhi new jaisa.'),
(222, 'Quality bohot solid hai, office use ke baad bhi new jaisa.'),
(223, 'Quality bohot solid hai, travel use ke baad bhi new jaisa.'),
(224, 'Quality bohot solid hai, weekend use ke baad bhi new jaisa.'),
(225, 'Quality bohot solid hai, gift use ke baad bhi new jaisa.'),
(226, 'Quality bohot solid hai, college use ke baad bhi new jaisa.'),
(227, 'Quality bohot solid hai, shaadi use ke baad bhi new jaisa.'),
(228, 'Quality bohot solid hai, summer use ke baad bhi new jaisa.'),
(229, 'Quality bohot solid hai, winter use ke baad bhi new jaisa.'),
(230, 'Quality bohot solid hai, monsoon use ke baad bhi new jaisa.'),
(231, 'Quality bohot solid hai, Eid use ke baad bhi new jaisa.'),
(232, 'Quality bohot solid hai, trip use ke baad bhi new jaisa.'),
(233, 'Quality bohot solid hai, meeting use ke baad bhi new jaisa.'),
(234, 'Quality bohot solid hai, brunch use ke baad bhi new jaisa.'),
(235, 'Quality bohot solid hai, evening use ke baad bhi new jaisa.'),
(236, 'Quality bohot solid hai, formal use ke baad bhi new jaisa.'),
(237, 'Quality bohot solid hai, casual use ke baad bhi new jaisa.'),
(238, 'Quality bohot solid hai, city use ke baad bhi new jaisa.'),
(239, 'Quality bohot solid hai, long use ke baad bhi new jaisa.'),
(240, 'Quality bohot solid hai, short use ke baad bhi new jaisa.'),
(241, 'Design classy hai — roz ke liye bilkul perfect choice.'),
(242, 'Design classy hai — office ke liye bilkul perfect choice.'),
(243, 'Design classy hai — travel ke liye bilkul perfect choice.'),
(244, 'Design classy hai — weekend ke liye bilkul perfect choice.'),
(245, 'Design classy hai — gift ke liye bilkul perfect choice.'),
(246, 'Design classy hai — college ke liye bilkul perfect choice.'),
(247, 'Design classy hai — shaadi ke liye bilkul perfect choice.'),
(248, 'Design classy hai — summer ke liye bilkul perfect choice.'),
(249, 'Design classy hai — winter ke liye bilkul perfect choice.'),
(250, 'Design classy hai — monsoon ke liye bilkul perfect choice.'),
(251, 'Design classy hai — Eid ke liye bilkul perfect choice.'),
(252, 'Design classy hai — trip ke liye bilkul perfect choice.'),
(253, 'Design classy hai — meeting ke liye bilkul perfect choice.'),
(254, 'Design classy hai — brunch ke liye bilkul perfect choice.'),
(255, 'Design classy hai — evening ke liye bilkul perfect choice.'),
(256, 'Design classy hai — formal ke liye bilkul perfect choice.'),
(257, 'Design classy hai — casual ke liye bilkul perfect choice.'),
(258, 'Design classy hai — city ke liye bilkul perfect choice.'),
(259, 'Design classy hai — long ke liye bilkul perfect choice.'),
(260, 'Design classy hai — short ke liye bilkul perfect choice.'),
(261, 'Packaging neat thi aur product roz condition me mila.'),
(262, 'Packaging neat thi aur product office condition me mila.'),
(263, 'Packaging neat thi aur product travel condition me mila.'),
(264, 'Packaging neat thi aur product weekend condition me mila.'),
(265, 'Packaging neat thi aur product gift condition me mila.'),
(266, 'Packaging neat thi aur product college condition me mila.'),
(267, 'Packaging neat thi aur product shaadi condition me mila.'),
(268, 'Packaging neat thi aur product summer condition me mila.'),
(269, 'Packaging neat thi aur product winter condition me mila.'),
(270, 'Packaging neat thi aur product monsoon condition me mila.'),
(271, 'Packaging neat thi aur product Eid condition me mila.'),
(272, 'Packaging neat thi aur product trip condition me mila.'),
(273, 'Packaging neat thi aur product meeting condition me mila.'),
(274, 'Packaging neat thi aur product brunch condition me mila.'),
(275, 'Packaging neat thi aur product evening condition me mila.'),
(276, 'Packaging neat thi aur product formal condition me mila.'),
(277, 'Packaging neat thi aur product casual condition me mila.'),
(278, 'Packaging neat thi aur product city condition me mila.'),
(279, 'Packaging neat thi aur product long condition me mila.'),
(280, 'Packaging neat thi aur product short condition me mila.'),
(281, 'Strap soft hai, roz carry karna easy rehta hai.'),
(282, 'Strap soft hai, office carry karna easy rehta hai.'),
(283, 'Strap soft hai, travel carry karna easy rehta hai.'),
(284, 'Strap soft hai, weekend carry karna easy rehta hai.'),
(285, 'Strap soft hai, gift carry karna easy rehta hai.'),
(286, 'Strap soft hai, college carry karna easy rehta hai.'),
(287, 'Strap soft hai, shaadi carry karna easy rehta hai.'),
(288, 'Strap soft hai, summer carry karna easy rehta hai.'),
(289, 'Strap soft hai, winter carry karna easy rehta hai.'),
(290, 'Strap soft hai, monsoon carry karna easy rehta hai.'),
(291, 'Strap soft hai, Eid carry karna easy rehta hai.'),
(292, 'Strap soft hai, trip carry karna easy rehta hai.'),
(293, 'Strap soft hai, meeting carry karna easy rehta hai.'),
(294, 'Strap soft hai, brunch carry karna easy rehta hai.'),
(295, 'Strap soft hai, evening carry karna easy rehta hai.'),
(296, 'Strap soft hai, formal carry karna easy rehta hai.'),
(297, 'Strap soft hai, casual carry karna easy rehta hai.'),
(298, 'Strap soft hai, city carry karna easy rehta hai.'),
(299, 'Strap soft hai, long carry karna easy rehta hai.'),
(300, 'Strap soft hai, short carry karna easy rehta hai.'),
(301, 'Color tone soft hai, roz outfits ke sath match ho jata hai.'),
(302, 'Color tone soft hai, office outfits ke sath match ho jata hai.'),
(303, 'Color tone soft hai, travel outfits ke sath match ho jata hai.'),
(304, 'Color tone soft hai, weekend outfits ke sath match ho jata hai.'),
(305, 'Color tone soft hai, gift outfits ke sath match ho jata hai.'),
(306, 'Color tone soft hai, college outfits ke sath match ho jata hai.'),
(307, 'Color tone soft hai, shaadi outfits ke sath match ho jata hai.'),
(308, 'Color tone soft hai, summer outfits ke sath match ho jata hai.'),
(309, 'Color tone soft hai, winter outfits ke sath match ho jata hai.'),
(310, 'Color tone soft hai, monsoon outfits ke sath match ho jata hai.'),
(311, 'Color tone soft hai, Eid outfits ke sath match ho jata hai.'),
(312, 'Color tone soft hai, trip outfits ke sath match ho jata hai.'),
(313, 'Color tone soft hai, meeting outfits ke sath match ho jata hai.'),
(314, 'Color tone soft hai, brunch outfits ke sath match ho jata hai.'),
(315, 'Color tone soft hai, evening outfits ke sath match ho jata hai.'),
(316, 'Color tone soft hai, formal outfits ke sath match ho jata hai.'),
(317, 'Color tone soft hai, casual outfits ke sath match ho jata hai.'),
(318, 'Color tone soft hai, city outfits ke sath match ho jata hai.'),
(319, 'Color tone soft hai, long outfits ke sath match ho jata hai.'),
(320, 'Color tone soft hai, short outfits ke sath match ho jata hai.'),
(321, 'Size balanced hai, roz essentials comfortably aa jate hain.'),
(322, 'Size balanced hai, office essentials comfortably aa jate hain.'),
(323, 'Size balanced hai, travel essentials comfortably aa jate hain.'),
(324, 'Size balanced hai, weekend essentials comfortably aa jate hain.'),
(325, 'Size balanced hai, gift essentials comfortably aa jate hain.'),
(326, 'Size balanced hai, college essentials comfortably aa jate hain.'),
(327, 'Size balanced hai, shaadi essentials comfortably aa jate hain.'),
(328, 'Size balanced hai, summer essentials comfortably aa jate hain.'),
(329, 'Size balanced hai, winter essentials comfortably aa jate hain.'),
(330, 'Size balanced hai, monsoon essentials comfortably aa jate hain.'),
(331, 'Size balanced hai, Eid essentials comfortably aa jate hain.'),
(332, 'Size balanced hai, trip essentials comfortably aa jate hain.'),
(333, 'Size balanced hai, meeting essentials comfortably aa jate hain.'),
(334, 'Size balanced hai, brunch essentials comfortably aa jate hain.'),
(335, 'Size balanced hai, evening essentials comfortably aa jate hain.'),
(336, 'Size balanced hai, formal essentials comfortably aa jate hain.'),
(337, 'Size balanced hai, casual essentials comfortably aa jate hain.'),
(338, 'Size balanced hai, city essentials comfortably aa jate hain.'),
(339, 'Size balanced hai, long essentials comfortably aa jate hain.'),
(340, 'Size balanced hai, short essentials comfortably aa jate hain.'),
(341, 'Finishing premium lagi, roz market bags se clear farq.'),
(342, 'Finishing premium lagi, office market bags se clear farq.'),
(343, 'Finishing premium lagi, travel market bags se clear farq.'),
(344, 'Finishing premium lagi, weekend market bags se clear farq.'),
(345, 'Finishing premium lagi, gift market bags se clear farq.'),
(346, 'Finishing premium lagi, college market bags se clear farq.'),
(347, 'Finishing premium lagi, shaadi market bags se clear farq.'),
(348, 'Finishing premium lagi, summer market bags se clear farq.'),
(349, 'Finishing premium lagi, winter market bags se clear farq.'),
(350, 'Finishing premium lagi, monsoon market bags se clear farq.'),
(351, 'Finishing premium lagi, Eid market bags se clear farq.'),
(352, 'Finishing premium lagi, trip market bags se clear farq.'),
(353, 'Finishing premium lagi, meeting market bags se clear farq.'),
(354, 'Finishing premium lagi, brunch market bags se clear farq.'),
(355, 'Finishing premium lagi, evening market bags se clear farq.'),
(356, 'Finishing premium lagi, formal market bags se clear farq.'),
(357, 'Finishing premium lagi, casual market bags se clear farq.'),
(358, 'Finishing premium lagi, city market bags se clear farq.'),
(359, 'Finishing premium lagi, long market bags se clear farq.'),
(360, 'Finishing premium lagi, short market bags se clear farq.'),
(361, 'Worth buying — roz ke hisaab se value zabardast hai.'),
(362, 'Worth buying — office ke hisaab se value zabardast hai.'),
(363, 'Worth buying — travel ke hisaab se value zabardast hai.'),
(364, 'Worth buying — weekend ke hisaab se value zabardast hai.'),
(365, 'Worth buying — gift ke hisaab se value zabardast hai.'),
(366, 'Worth buying — college ke hisaab se value zabardast hai.'),
(367, 'Worth buying — shaadi ke hisaab se value zabardast hai.'),
(368, 'Worth buying — summer ke hisaab se value zabardast hai.'),
(369, 'Worth buying — winter ke hisaab se value zabardast hai.'),
(370, 'Worth buying — monsoon ke hisaab se value zabardast hai.'),
(371, 'Worth buying — Eid ke hisaab se value zabardast hai.'),
(372, 'Worth buying — trip ke hisaab se value zabardast hai.'),
(373, 'Worth buying — meeting ke hisaab se value zabardast hai.'),
(374, 'Worth buying — brunch ke hisaab se value zabardast hai.'),
(375, 'Worth buying — evening ke hisaab se value zabardast hai.'),
(376, 'Worth buying — formal ke hisaab se value zabardast hai.'),
(377, 'Worth buying — casual ke hisaab se value zabardast hai.'),
(378, 'Worth buying — city ke hisaab se value zabardast hai.'),
(379, 'Worth buying — long ke hisaab se value zabardast hai.'),
(380, 'Worth buying — short ke hisaab se value zabardast hai.'),
(381, 'Look elegant hai aur roz daily wear me practical bhi.'),
(382, 'Look elegant hai aur office daily wear me practical bhi.'),
(383, 'Look elegant hai aur travel daily wear me practical bhi.'),
(384, 'Look elegant hai aur weekend daily wear me practical bhi.'),
(385, 'Look elegant hai aur gift daily wear me practical bhi.'),
(386, 'Look elegant hai aur college daily wear me practical bhi.'),
(387, 'Look elegant hai aur shaadi daily wear me practical bhi.'),
(388, 'Look elegant hai aur summer daily wear me practical bhi.'),
(389, 'Look elegant hai aur winter daily wear me practical bhi.'),
(390, 'Look elegant hai aur monsoon daily wear me practical bhi.'),
(391, 'Look elegant hai aur Eid daily wear me practical bhi.'),
(392, 'Look elegant hai aur trip daily wear me practical bhi.'),
(393, 'Look elegant hai aur meeting daily wear me practical bhi.'),
(394, 'Look elegant hai aur brunch daily wear me practical bhi.'),
(395, 'Look elegant hai aur evening daily wear me practical bhi.'),
(396, 'Look elegant hai aur formal daily wear me practical bhi.'),
(397, 'Look elegant hai aur casual daily wear me practical bhi.'),
(398, 'Look elegant hai aur city daily wear me practical bhi.'),
(399, 'Look elegant hai aur long daily wear me practical bhi.'),
(400, 'Look elegant hai aur short daily wear me practical bhi.'),
(401, 'Ateeqo se khush hun, roz order definitely recommend.'),
(402, 'Ateeqo se khush hun, office order definitely recommend.'),
(403, 'Ateeqo se khush hun, travel order definitely recommend.'),
(404, 'Ateeqo se khush hun, weekend order definitely recommend.'),
(405, 'Ateeqo se khush hun, gift order definitely recommend.'),
(406, 'Ateeqo se khush hun, college order definitely recommend.'),
(407, 'Ateeqo se khush hun, shaadi order definitely recommend.'),
(408, 'Ateeqo se khush hun, summer order definitely recommend.'),
(409, 'Ateeqo se khush hun, winter order definitely recommend.'),
(410, 'Ateeqo se khush hun, monsoon order definitely recommend.'),
(411, 'Ateeqo se khush hun, Eid order definitely recommend.'),
(412, 'Ateeqo se khush hun, trip order definitely recommend.'),
(413, 'Ateeqo se khush hun, meeting order definitely recommend.'),
(414, 'Ateeqo se khush hun, brunch order definitely recommend.'),
(415, 'Ateeqo se khush hun, evening order definitely recommend.'),
(416, 'Ateeqo se khush hun, formal order definitely recommend.'),
(417, 'Ateeqo se khush hun, casual order definitely recommend.'),
(418, 'Ateeqo se khush hun, city order definitely recommend.'),
(419, 'Ateeqo se khush hun, long order definitely recommend.'),
(420, 'Ateeqo se khush hun, short order definitely recommend.');

DROP TEMPORARY TABLE IF EXISTS tmp_nums;
CREATE TEMPORARY TABLE tmp_nums (n INT NOT NULL PRIMARY KEY);
INSERT INTO tmp_nums (n) VALUES
(1),(2),(3),(4),(5),(6),(7),(8),(9),(10),
(11),(12),(13),(14),(15),(16),(17),(18),(19),(20);

-- Har product: random 10–20 reviews
DROP TEMPORARY TABLE IF EXISTS tmp_product_targets;
CREATE TEMPORARY TABLE tmp_product_targets AS
SELECT
  p.id AS product_id,
  10 + FLOOR(RAND(p.id * 97 + 13) * 11) AS target_count
FROM products p;

-- Unique pick per (product_id, n):
-- step 13 / 17 ensures same product ke andar duplicate text/name na aaye
INSERT INTO product_reviews (product_id, reviewer, reviewer_email, review, rating, status, created_at)
SELECT
  t.product_id,
  rv.reviewer,
  CONCAT(
    LOWER(REPLACE(rv.reviewer, ' ', '.')),
    '.',
    t.product_id,
    '.',
    n.n,
    '@gmail.com'
  ) AS reviewer_email,
  rt.review_text,
  CASE
    WHEN ((t.product_id + n.n) % 5) = 0 THEN 4
    WHEN ((t.product_id + n.n) % 7) = 0 THEN 4
    WHEN ((t.product_id * n.n) % 11) = 0 THEN 4
    ELSE 5
  END AS rating,
  'approved',
  DATE_SUB(NOW(), INTERVAL ((t.product_id * 3 + n.n * 11) % 120) DAY)
    - INTERVAL ((t.product_id * 5 + n.n * 7) % 23) HOUR
FROM tmp_product_targets t
CROSS JOIN tmp_nums n
INNER JOIN tmp_reviewers rv
  ON rv.rid = ((t.product_id * 41 + (n.n - 1) * 17) % 90) + 1
INNER JOIN tmp_review_texts rt
  ON rt.tid = ((t.product_id * 53 + (n.n - 1) * 13) % 420) + 1
WHERE n.n <= t.target_count;

COMMIT;

SELECT
  p.id,
  p.name,
  COUNT(r.id) AS review_count,
  ROUND(AVG(r.rating), 2) AS avg_rating,
  COUNT(DISTINCT r.review) AS unique_reviews
FROM products p
LEFT JOIN product_reviews r ON r.product_id = p.id AND r.status = 'approved'
GROUP BY p.id, p.name
ORDER BY p.id;

SELECT review_count, COUNT(*) AS products
FROM (
  SELECT p.id, COUNT(r.id) AS review_count
  FROM products p
  LEFT JOIN product_reviews r ON r.product_id = p.id
  GROUP BY p.id
) x
GROUP BY review_count
ORDER BY review_count;
